### ISSUE TITLE
Interested in building the app

### ISSUE THREAD

**Issue by vdegenne** [kevinpschaaf/polymer-re#1]
@kevinpschaaf Hello Kevin, I am interested in building this project of yours for education purpose.
I try to keep informed about the latest possible ways of building better and progressive web-apps. I was first surprised to see js files in the src directory as polymer-cli only deals with html files, and in fact when I tried to `polymer build` the project, the "my-app.html" was nowhere to be found. I would really appreciate if you could take a small time to explain the building workflow of this project or provide the files for the compilation process.

Best Regards

**Comment by kevinpschaaf** [comment]
This is all experimental, it's not a fully usable demo yet (can't be built, uses some ES next features, etc.), just trying out different patterns for development to help influence future direction.  For now, I'd stick to e.g. shop/news demos and polymer-starter-kit for well-supported educational material.
